name: Testes do GitLab CE com Cypress

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      gitlab-ce:
        image: wlsf82/gitlab-ce
        ports:
          - 80:80
          - 2222:22  # Mapeando a porta SSH para a porta 2222
        options: --hostname localhost

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Esperar pelo GitLab CE
      run: |
        until docker inspect -f '{{.State.Health.Status}}' ${{ job.services.gitlab-ce.id }} | grep -q healthy; do
          sleep 5
        done

    - name: Instalar Cypress
      run: npm install cypress

    - name: Executar testes Cypress
      run: ./node_modules/.bin/cypress run --spec "cypress/e2e/GUI/" --browser chrome --headless --config baseUrl=http://localhost
