name: Testes Cypress

on:
  push:
    branches:
      - main  # Substitua "main" pelo nome do seu branch principal, se necessário

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Instalar Cypress
        run: npm install cypress --save-dev

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: npm run cypress:run
