name: Testes do GitLab CE com Cypress

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      gitlab-ce:
        image: wlsf82/gitlab-ce
        ports:
          - 80:80
          - 2222:22  # Mapeando a porta SSH para a porta 2222
        options: --hostname localhost

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Esperar pelo GitLab CE
      run: sleep 120   # Aumentamos o tempo de espera para 120 segundos para garantir que o GitLab CE esteja pronto

    - name: Verificar status do GitLab CE
      run: docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" gitlab-ce

    - name: Instalar Cypress
      run: npm install cypress

    - name: Executar testes Cypress
      run: ./node_modules/.bin/cypress run --browser chrome --headless --config baseUrl=http://localhost
